(cl:defpackage frontier_exploration-srv
  (:use )
  (:export
   "UPDATEBOUNDARYPOLYGON"
   "<UPDATEBOUNDARYPOLYGON-REQUEST>"
   "UPDATEBOUNDARYPOLYGON-REQUEST"
   "<UPDATEBOUNDARYPOLYGON-RESPONSE>"
   "UPDATEBOUNDARYPOLYGON-RESPONSE"
   "GETNEXTFRONTIER"
   "<GETNEXTFRONTIER-REQUEST>"
   "GETNEXTFRONTIER-REQUEST"
   "<GETNEXTFRONTIER-RESPONSE>"
   "GETNEXTFRONTIER-RESPONSE"
  ))

